### ISSUE TITLE
UI should support concept classes and datatypes not in the lookup tables

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#122] opened 2017-10-04 01:46 UTC
Eventually, each source will be able to control which values are allowed in the lookup tables. Right now, the API allows any value in the lookup fields (concept class, datatype, name type, etc.) unless a Custom Validation Schema is selected (currently only OpenMRS exists). The lookup lists are populated by sources in the OCL organization (e.g. /orgs/OCL/sources/Datatypes/concepts/).

However, the UI does not support custom values, and that means that it is basically not possible to edit resources in the UI without losing the custom value.

PEPFAR uses custom values for concept classes in most/all of its sources.

**Comment by paynejd** [comment] 2017-10-04 01:47
@davetrig Assigning this to you, because this could be a good next one. Will discuss remaining bandwidth with Carol in case we should hold off...

**Comment by paynejd** [comment] 2017-10-04 17:06
@davetrig There are actually 8 lookup tables used in OCL that are stored in repositories under the OCL organization (see here: https://www.openconceptlab.org/orgs/OCL/sources/). Eventually we should update the entire UI to support use of dropdowns plus a text field for custom values for fields that use any of these 8 of these lookup tables. That's potentially a big task, though. So, here are the XS, small, medium, large and XXL options for resolving this as far as I can tell -- after you have a chance to review, let me know which you think makes the most sense to take on.  I'm assuming we'll go with the XS approach and then we'll create tickets for the others.

0. [Extra Small] Support custom values for concept classes and concept datatypes -- these are the most important
1. [Small] Support custom values just for all lookup fields for concepts (nametype, descriptiontype, locale, class, datatype)
2. [Medium] Support custom values for lookups for concepts and mappings (maptype)
3. [Large] Support custom values for all lookups in the UI
4. [XXL] Allow each repository to choose which repositories it uses to populate lookup values and whether custom values are allowed

**Comment by davetrig** [comment] 2017-10-18 01:16
@paynejd I was delayed getting this finished up due to bug found with Issue 119.  Should have it ready EOB Wednesday.

**Comment by davetrig** [comment] 2017-10-18 19:51
@paynejd & @rkorytkowski 
I've submitted a pull request that includes the update entry fields on the New and Edit Concept screens for Concept Class and Datatype.  
I'm continuing to work to apply these changes to other fields.

**Comment by davetrig** [comment] 2017-10-19 17:14
I've added a commit that extends the new input field to concept mapping map type

**Comment by davetrig** [comment] 2017-10-20 18:45
I've made the final commits to complete this item.  All should be in the existing pull request on ocl_web.

Unfortunately, I was unable to make my sexy dropdown combo boxes in the Concept Name & Description locale and type fields.  It's possible that with more time it could be made to work, but I've spun my wheels in it enough for now.  I've changed these input fields to HTML5 inputs with linked datalists.  This is decidedly less sexy, but it will at least support non-standard values in the fields.

**Comment by davetrig** [comment] 2017-10-20 19:24
@paynejd - I also included a cool autocomplete field for supported locales on the source and collection forms.  Check it out - it's good stuff.

**Comment by paynejd** [comment] 2017-10-24 18:53
@davetrig Look forward to checking it out after it is deployed to showcase! (I'm not set up to do this locally yet...)

**Comment by rkorytkowski** [comment] 2017-10-30 14:15
Unit tests fail at https://ci.openmrs.org/browse/OCL-OW-84
In order to reproduce it locally you need to run tests without having the oclapi server started. The new code requires connection to the oclapi when testing views. We need to find a way to run tests without having to run oclapi. See e.g.

```
ImportError: Failed to import test module: ocl_web.apps.sources.test_views
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/code/ocl_web/apps/sources/test_views.py", line 4, in <module>
    from apps.sources.forms import  SourceDeleteForm
  File "/code/ocl_web/apps/sources/forms.py", line 14, in <module>
    class SourceNewForm(forms.Form):
  File "/code/ocl_web/apps/sources/forms.py", line 58, in SourceNewForm
    widget=ComboBoxWidget(data_list=[[l['code'], l['name']] for l in _get_locale_list()], name="default_locale_list")
  File "/code/ocl_web/apps/core/views.py", line 284, in _get_locale_list
    response = api.get('orgs', 'OCL', 'sources', 'Locales', 'concepts', params={'limit': 0})
  File "/code/ocl_web/libs/ocl/__init__.py", line 207, in get
    results = requests.get(self.url, params=params, headers=self.headers)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='172.17.0.1', port=8000): Max retries exceeded with url: /orgs/OCL/sources/Locales/concepts/?limit=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa22a0b9290>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by davetrig** [comment] 2017-10-30 19:47
@rkorytkowski & @paynejd 
I didn't change where the data was coming from -- the choice fields were previously also populated from _get_locale_list() -- so my question is, how was this not failing previous to my commits?

Also, I'm not convinced that you _can_ run this test without connection to the API, since the values in the either the SELECT elements (as was used previously) or in JavaScript arrays (as I'm doing now) both come from the API.  So how would you expect to test the forms without the API running?

**Comment by rkorytkowski** [comment] 2017-10-31 10:30
API requests are mocked out in tests so tests do not depend on having the API running. See the use of @patch and MagicMock at e.g. https://github.com/OpenConceptLab/ocl_web/blob/master/ocl_web/apps/sources/test_views.py#L18-L22 
You actually added calls to _get_locale_list() in some forms, which were not mocked in tests e.g. https://github.com/OpenConceptLab/ocl_web/blob/master/ocl_web/apps/sources/forms.py#L65.

**Comment by rkorytkowski** [comment] 2017-10-31 11:29
I noticed some tests were failing even if a form wasn't used in a test. It is due to the fact that you created widgets on field declarations, which caused http requests on loading a module i.e. even before running a test. I moved all these declarations to __init__ methods and no extra mocking was needed. See https://github.com/OpenConceptLab/ocl_web/commit/5a06a27af89052c932f592f71948baa4f76e23db

**Comment by rkorytkowski** [comment] 2017-10-31 12:12
Deployed to qa. Personally I do not like the dropdown behavior. For example the default list is long so I tend to type a few first letters e.g. 'en'. It only highlights matching elements with yellow instead of filtering the list out for me. I still need to scroll the whole list to find the one I need.

**Comment by rkorytkowski** [comment] 2017-10-31 13:10
UI tests are failing now: https://ci.openmrs.org/download/OCL-OUT-JOB1/build_logs/OCL-OUT-JOB1-55.log

**Comment by paynejd** [comment] 2017-10-31 17:46
A few issues:
* Sources
    * Public Access & Custom Validation Schema must restrict values to the dropdown options
    * An example underneath Default Locale would be good too -- (e.g. "en") -- also why not default this field to "en"?
    * Supported Locales is a big improvement, because it assists in the multi-selection process -- please add a note underneath that gives an example of what the right content looks like (e.g. "en,fr,sw") -- also why not default this field to "en" also?

I then ran into system errors which would not allow me to test any further -- I could not browse to the concepts/mappings pages for the source I just created: https://qa.openconceptlab.org/orgs/hello/sources/mysource/concepts/

**Comment by rkorytkowski** [comment] 2017-11-02 10:16
@paynejd, do you still see system errors? In Sentry we have 3 different errors logged 2 days ago. Did you try more times? If yes, then they may not have been logged or they happened on the ocl_web side, which is not yet configured to push to sentry.

**Comment by paynejd** [comment] 2017-11-02 12:01
The error is still occurring when I go here:
https://qa.openconceptlab.org/orgs/hello/sources/mysource/concepts/

**Comment by paynejd** [comment] 2017-11-02 12:02
If you go to the API, it's correctly returning zero concepts:
https://api.qa.openconceptlab.org/orgs/hello/sources/mysource/concepts/

And zero mappings:
https://api.qa.openconceptlab.org/orgs/hello/sources/mysource/mappings/

**Comment by rkorytkowski** [comment] 2017-11-03 14:24
Strangely, it works for me. I'm logged in as admin. What user are you using?

**Comment by rkorytkowski** [comment] 2017-11-13 13:50
@davetrig did you get a chance to look into @paynejd  comments and failing UI tests?

**Comment by paynejd** [comment] 2017-11-13 13:55
Just tested again and this error is still happening. See comments above

**Comment by davetrig** [comment] 2017-11-27 21:36
Changed Public Access and Custom Validation Schema fields back to SELECT fields, and submitted pull request.

**Comment by rkorytkowski** [comment] 2017-12-05 10:57
I'll work on fixing UI tests....

**Comment by rkorytkowski** [comment] 2017-12-05 12:32
@davetrig, I found two issues.
1) When creating/editing a concept, you can type any value in a locale name field, whereas it should be restricted to supported locales for a source. The default is not selected either.
2) When creating a source, you can type in a default locale, which is not in a supported locales list.

**Comment by davetrig** [comment] 2017-12-05 14:44
@rkorytkowski, The whole idea is to support values that are not in the lookup tables.  @paynejd and I discussed this approach of using auto-complete text fields rather than restrictive dropdowns to address this issue, and we determined that the benefits outweighed the shortcomings.

New concepts were not previously pre-populated with the repository's default locale.  If we want that, then that's a new requirement which should be addressed in a future "GUI improvements" ticket.

**Comment by paynejd** [comment] 2017-12-05 14:57
Agree that #2 would be a new requirement -- I would suggest creating a
ticket for this, as I think more important for Dave to focus on the
collection membership queries.

For #1, I knew that PIH was using non-standard locales (e.g. en-GB), so
rather than solve that problem, we thought that a short-term approach would
be to simply not restrict the values. This is obviously not a good
long-term solution, but seemed okay for now. I would suggest that we create
a ticket for improved locale management and close this ticket out.

**Comment by rkorytkowski** [comment] 2018-01-11 13:56
UI tests fixed! I needed to ignore 3 of them as I couldn't make them work for some reason. The features do work when I test them manually though.  There was a lot of failures due to defaults not being selected when creating a new concept/source/collection e.g. concept datatype, concept class, supported locales, default locale, etc. See https://ci.openmrs.org/browse/OCL-OUT/latest

As it stands now we can't run UI tests in a browser on Windows, thus it's hard to see what's actually wrong. We will need to revisit the ui testing framework to be able to easily run them on Linux/Mac/Windows.

**Closed** 2018-02-21 23:51 UTC
